# Define update file action workflow
# Events + Jobs + Runners + Steps + Actions
# Events = something that trigger the workflow like on: push 
# Jobs = job runs on triggered event
# Runner = container env that runs the code like runs-on
# Steps = step of a job
# Actions = action of that step
name: Update and Download Yaml file
on: 
  push:
    branches: 
      - main

jobs: 
  update-and-download:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    # Step to get list of yaml files 
    - name: Get list of updated savedFilter files
      id: list-files
      run: |
        export current_commit=github.sha
        export changed_files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
        echo "current commit is ${{github.sha}}"
        echo "List of files is $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
        echo "changed files: $changed_files"
        echo "files=$changed_files" >> $GITHUB_OUTPUT
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
    
    - name: Run python script
      run: |
        echo "Hello! This files are updated ${{ steps.list-files.files }}"


