# Define update file action workflow
# Events + Jobs + Runners + Steps + Actions
# Events = something that trigger the workflow like on: push 
# Jobs = job runs on triggered event
# Runner = container env that runs the code like runs-on
# Steps = step of a job
# Actions = action of that step
name: Update and Download Yaml file
on: 
  push:
    branches: 
      - main

jobs: 
  update-and-download:
    runs-on: ubuntu-latest
    steps:
    # The default git checkout has fetch-depth = 1 meaning it's checkout the lastet commit 
    # Change to 0 to fetch the whole commit history
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
    
    - name: Run python script
      id: update_yaml
      run: |
        git config --global user.email "leminhthang.tnl@gmail.com"
        git config --global user.name "Thang-sudo"
        python update-yaml.py
      working-directory: ${{ github.workspace }}
    
    - name: Get Updated files
      run: echo ${{ steps.update_yaml.outputs.downloaded_files }}
    
    - name: Upload updated files
      uses: actions/upload-artifact@v2
      with:
        name: updated-yaml
        path: ./savedFilters/*
    - name: Download artifacts
      uses: action/download-artifact@v2
      with:
        name: updated-yaml
        path: ./artifacts



